name: 'JianHuang' 
on:
#  push: 
  watch:
    types: started
jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - name: 'Ready'
        run: |
          wget https://github.com/lem0nb/jianhuang/raw/master/webBenchmark_linux_x64 -O jh
          chmod +x jh
      - name: 'Start JianHuang'
        run: |
          ./jh -c ${{ secrets.XC }} -s ${{ secrets.URL }}
 
